name: cat_food_reviews
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  async: ^2.13.0
  clock: ^1.1.2
  collection: ^1.19.1
  dart_jsonwebtoken: ^3.3.1
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  drift: ^2.29.0
  firebase_analytics: ^12.1.0
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^16.2.5
  http: ^1.5.0
  # flutter_localizationsに依存したバージョンを採用するため、anyを指定
  intl: any
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  logger: ^2.6.2
  package_info_plus: ^9.0.0
  # データベースファイルのパス操作
  path: ^1.9.1
  # データベースファイルの保存先取得
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.0
  riverpod_annotation: ^3.0.3
  sentry_flutter: ^9.9.1
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.40
  theme_tailor_annotation: ^3.0.3
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: any
  drift_dev: ^2.29.0
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  go_router_builder: ^4.1.0
  mocktail: ^1.0.4
  riverpod: ^3.0.3
  riverpod_generator: ^3.0.3
  riverpod_lint: any
  sentry_dart_plugin: ^3.2.0
  theme_tailor: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  # ローカライズに関するファイル生成用
  generate: true

flutter_gen:
  output: lib/gen
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/main_theme.png"
  
  # Adaptive Icon設定（Android 8.0+用）
  adaptive_icon_background: "#F7F6F2"  # クリーム色の背景
  adaptive_icon_foreground: "assets/images/main_theme.png"  # 前景にメイン画像
  min_sdk_android: 21

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: 7ded66c71e1b
